### ISSUE TITLE
RuntimeError - Unable to find subscription with identifier

### ISSUE THREAD

**Issue by Martouta** [tomekw/ac-issue#2]
I have exactly the same error and also broadcasting in the subscribed block, could you fix it? Thanks!

**Comment by tomekw** [comment]
Hello @Martouta! The fix has been merged into Rails but it wasn't released yet. To get the fix you should move from `5.0.0.1` release to `5-0-stable` branch. It can be done like this in the `Gemfile`:

```
gem "rails", github: "rails/rails", branch: "5-0-stable"
```

Hope this helps.

Also, it's also a hint you may be doing too much indeed in the `subscribed` block.

**Comment by Martouta** [comment]
In my case it was because I had the file config/cable.yml in /config/redis/cable.yml, but when I changed it, it worked. Thank you anyway, I appreciate your help.
